SELECT DISTINCT 
				ZZ1_STATUS, 
				ZZ0_VENDED	AS VENDEDOR,
				A3_NOME		AS NOMEVEND,
				ZZ0_PRODUT	AS PRODUTO,
				B1_DESC		AS DESCRPROD,
				
				(SELECT (
					CASE WHEN SUM(Z10.ZZ0_QUANTI) IS NULL 
					THEN 0 
					ELSE SUM(Z10.ZZ0_QUANTI) END) AS QTDE
				FROM ZZ0010 Z10 
				WHERE Z10.ZZ0_VENDED = Z0.ZZ0_VENDED
				AND Z10.ZZ0_PRODUT = Z0.ZZ0_PRODUT
				AND Z10.ZZ0_CODCOT = ZZ8_CODIGO
				AND Z10.ZZ0_TIPOMO = 'E'
				AND Z10.ZZ0_MOTIVO <> 'T'
				AND Z10.D_E_L_E_T_ = ''
				AND Z10.ZZ0_STATUS = 'A') AS COTATOTAL,

				(SELECT ( 
					CASE WHEN SUM(ZZ0_QUANTI) IS NULL
					THEN 0
					ELSE SUM(ZZ0_QUANTI) END) AS QTDE
				FROM ZZ0010 Z50
				WHERE Z50.ZZ0_VENDED = Z0.ZZ0_VENDED
				AND Z50.ZZ0_PRODUT = Z0.ZZ0_PRODUT
				AND Z50.ZZ0_CODCOT = ZZ8_CODIGO
				AND Z50.ZZ0_TIPOMO = 'E'
				AND Z50.ZZ0_MOTIVO = 'T'
				AND Z50.D_E_L_E_T_ = ''
				AND ZZ0_STATUS = 'A') AS COTATRANE,
				
				(SELECT (
					CASE WHEN SUM(ZZ0_QUANTI)*-1 IS NULL
					THEN 0
					ELSE SUM(ZZ0_QUANTI)*-1 END) AS QTDE
					FROM ZZ0010 Z20
					WHERE Z20.ZZ0_VENDED = Z0.ZZ0_VENDED
					AND Z20.ZZ0_PRODUT = Z0.ZZ0_PRODUT
					AND Z20.ZZ0_CODCOT = ZZ8_CODIGO
					AND Z20.ZZ0_TIPOMO = 'S'
					AND Z20.ZZ0_MOTIVO = 'T'
					AND Z20.D_E_L_E_T_ = ''
					AND Z0.ZZ0_STATUS = 'A') AS COTATRANS,
					
					(SELECT (
						CASE WHEN SUM(ZZ0_QUANTI)*-1 IS NULL
						THEN 0
						ELSE SUM(ZZ0_QUANTI)*-1 END) AS QTDE
						FROM ZZ0010 Z60
						WHERE Z60.ZZ0_VENDED = Z0.ZZ0_VENDED
						AND Z60.ZZ0_PRODUT = Z0.ZZ0_PRODUT
						AND Z60.ZZ0_CODCOT = ZZ8_CODIGO
						AND Z60.ZZ0_TIPOMO = 'S'
						AND Z60.ZZ0_MOTIVO <> 'T'
						AND Z60.D_E_L_E_T_ = ''
						AND ZZ0_STATUS = 'A') AS COTAUTILI,
						
						(
							SELECT (
								CASE WHEN SUM(ZZ0_QUANTI) IS NULL 
								THEN 0 
								ELSE SUM(ZZ0_QUANTI) END) AS QTDE 
								FROM ZZ0010 Z30 
								WHERE Z30.ZZ0_VENDED = Z0.ZZ0_VENDED
								AND Z30.ZZ0_PRODUT = Z0.ZZ0_PRODUT
								AND Z30.ZZ0_CODCOT = ZZ8_CODIGO 
								AND Z30.ZZ0_TIPOMO = 'E' 
								AND Z30.D_E_L_E_T_ = ''
								AND ZZ0_STATUS = 'A')
							-
								(SELECT (
									CASE WHEN SUM(ZZ0_QUANTI)*-1 IS NULL 
									THEN 0 
									ELSE SUM(ZZ0_QUANTI)*-1 END) AS QTDE 
									FROM ZZ0010 Z40 
									WHERE Z40.ZZ0_VENDED = Z0.ZZ0_VENDED 
									AND Z40.ZZ0_PRODUT = Z0.ZZ0_PRODUT 
									AND Z40.ZZ0_CODCOT = ZZ8_CODIGO 
									AND Z40.ZZ0_TIPOMO = 'S' 
									AND Z40.D_E_L_E_T_ = '' 
									AND ZZ0_STATUS = 'A'
									
									)
							 AS COTARESTA
							
	FROM ZZ8010 Z8	
	INNER JOIN ZZ0010 Z0 
		ON ZZ0_CODCOT = ZZ8_CODIGO 

	INNER JOIN SA3010 A3
		ON A3_COD = ZZ0_VENDED 

	INNER JOIN SB1010 B1 
		ON B1_COD = ZZ0_PRODUT 

	INNER JOIN ZZ1010 Z1 
		ON ZZ1_PRODUT = ZZ0_PRODUT

	WHERE ZZ8_STATUS = 'A' 
	--AND Z0.ZZ0_VENDED = %exp: cVend%
	AND ZZ0_STATUS = 'A'
	AND Z8.D_E_L_E_T_ = ''
	AND Z0.D_E_L_E_T_ = ''
	AND A3.D_E_L_E_T_ = ''
	AND B1.D_E_L_E_T_ = ''
	AND Z1.D_E_L_E_T_ = ''

	ORDER BY ZZ0_VENDED, ZZ0_PRODUT