SELECT DISTINCT
                D1.D1_FILIAL, SUBSTRING(D1_EMISSAO,7,2)+'/'+SUBSTRING(D1_EMISSAO,5,2)+'/'+SUBSTRING(D1_EMISSAO,1,4) AS D1_EMISSAO,
				SUBSTRING(D1_DTDIGIT,7,2)+'/'+SUBSTRING(D1_DTDIGIT,5,2)+'/'+SUBSTRING(D1_DTDIGIT,1,4) AS D1_DTDIGIT, F1.F1_TIPO ,
                D1.D1_ATSAC , D1.D1_FORNECE, D1.D1_LOJA   , A1.A1_NOME , D1.D1_LOCAL,
                A1.A1_GRPVEN, A1.A1_SEGCLI , D1.D1_LOTECTL, A1.A1_MUN  ,
                A1.A1_EST   , A1.A1_VEND   , D1.D1_DOC    , B1.B1_GRUPO,
                D1.D1_SERIE , D1.D1_COD    , B1.B1_DESC   , B1.B1_UM,
				
				(CASE
					WHEN
					(SELECT COUNT(CONCAT(UD_FILIAL,UD_CODIGO,UD_OCORREN,UD_S_DEPTO))
					FROM SUD010 UD
					WHERE UD.UD_CODIGO = D1.D1_ATSAC 
					AND UD.UD_FILIAL = D1.D1_FILIAL 
					AND UD.UD_PRODUTO = D1.D1_COD
					AND UD.UD_S_CODM = D1.D1_OCORREN
					AND UD.UD_S_MOTCA = D1.D1_DESCOCO
					AND UD.UD_QTDE = D1.D1_QUANT
					AND UD.D_E_L_E_T_ = ''
					) > 
					(SELECT COUNT(CONCAT(D1_FILIAL,D1_DOC,D1_SERIE,D1_COD,D1_NFORI,D1_SERIORI,D1_ITEMORI,D1_QUANT,D1_VUNIT,D1_NFORI))
					FROM SD1010 D1_SUB 
					WHERE D1_SUB.D1_DOC = D1.D1_DOC
					AND D1_SUB.D1_SERIE = D1.D1_SERIE
					AND D1_SUB.D1_FILIAL = D1.D1_FILIAL
					AND D1_SUB.D1_COD = D1.D1_COD
					AND D1_SUB.D1_QUANT = D1.D1_QUANT
					AND D1_SUB.D1_VUNIT = D1.D1_VUNIT
					AND D1_SUB.D1_NFORI = D1.D1_NFORI
					AND D1_SUB.D1_SERIORI = D1.D1_SERIORI
					AND D1_SUB.D1_ITEMORI = D1.D1_ITEMORI
					AND D1_SUB.D1_OCORREN = D1.D1_OCORREN
					AND D1_SUB.D1_DESCOCO = D1.D1_DESCOCO
					AND D1_SUB.D1_QUANT = UD.UD_QTDE
					GROUP BY CONCAT(D1_FILIAL,D1_DOC,D1_SERIE,D1_COD,D1_NFORI,D1_SERIORI,D1_ITEMORI,D1_QUANT,D1_VUNIT,D1_NFORI,D1_CC,D1_QUANT,D1_FILORI)
				)
				THEN (UD.UD_QTDE)						
				ELSE (D1.D1_QUANT)
				END) AS QUANTIDADE,
		
				(CASE 
					WHEN
					(SELECT COUNT(CONCAT(UD_FILIAL,UD_CODIGO,UD_QTDE,UD_OCORREN,UD_S_DEPTO))
					FROM SUD010 SUB_UD 
					WHERE SUB_UD.UD_CODIGO = D1.D1_ATSAC 
					AND SUB_UD.UD_FILIAL = D1.D1_FILIAL 
					AND SUB_UD.UD_PRODUTO = D1.D1_COD
					AND SUB_UD.UD_S_CODM = D1.D1_OCORREN
					AND SUB_UD.UD_QTDE = D1.D1_QUANT)
					> 
					(SELECT COUNT(CONCAT(D1_FILIAL,D1_DOC,D1_SERIE,D1_COD,D1_FORNECE,D1_LOJA,D1_NFORI,D1_SERIORI))
					FROM SD1010 SUB_D1 
					WHERE SUB_D1.D1_ATSAC = D1.D1_ATSAC
					AND SUB_D1.D1_FILIAL = D1.D1_FILIAL	
					AND SUB_D1.D1_SERIE = D1.D1_SERIE 
					AND SUB_D1.D1_FILIAL = D1.D1_FILIAL 
					AND SUB_D1.D1_COD = D1.D1_COD
					AND SUB_D1.D1_QUANT = D1.D1_QUANT
					AND SUB_D1.D1_VUNIT = D1.D1_VUNIT
					AND SUB_D1.D1_NFORI = D1.D1_NFORI
					AND SUB_D1.D1_SERIORI = D1.D1_SERIORI
					AND SUB_D1.D1_ITEMORI = D1.D1_ITEMORI
					AND SUB_D1.D1_QUANT = UD.UD_QTDE
					GROUP BY CONCAT(D1_FILIAL,D1_DOC,D1_SERIE,D1_COD,D1_NFORI,D1_SERIORI,D1_ITEMORI,D1_QUANT,D1_VUNIT,D1_NFORI,D1_CC))
				THEN 
					(CASE
						WHEN B1.B1_UM = 'PC'
						THEN UD.UD_QTDE * B1.B1_PSOPC
						WHEN B1.B1_UM = 'SC'
						THEN UD.UD_QTDE * B1.B1_PESO
						ELSE UD.UD_QTDE
					END)

					ELSE
					(CASE
						WHEN B1.B1_UM = 'PC'
							THEN D1.D1_QUANT * B1.B1_PSOPC
							WHEN B1.B1_UM = 'SC'
								THEN D1.D1_QUANT * B1.B1_PESO
							ELSE D1.D1_QUANT
					 END)
				END) AS PESO,   
                
				D1.D1_VUNIT, 
				
				(CASE 
					WHEN 
					(SELECT COUNT(CONCAT(UD_FILIAL,UD_CODIGO,UD_QTDE,UD_OCORREN,UD_S_DEPTO))
					FROM SUD010 UD 
					WHERE UD_CODIGO = D1.D1_ATSAC 
					AND UD_FILIAL = D1.D1_FILIAL 
					AND UD_PRODUTO = D1.D1_COD
					AND UD_QTDE = D1.D1_QUANT)
					> 
					(SELECT COUNT(CONCAT(D1_FILIAL, D1_EMISSAO, D1_DTDIGIT, D1_ATSAC, D1_FORNECE, D1_LOJA, D1_LOCAL, D1_LOTECTL, D1_DOC, D1_SERIE, D1_COD, D1_VUNIT, D1_TES, D1_NFORI))
					FROM SD1010 SUB_D1 
					WHERE SUB_D1.D1_DOC = D1.D1_DOC
					AND SUB_D1.D1_COD = D1.D1_COD
					AND SUB_D1.D1_SERIE = D1.D1_SERIE 
					AND SUB_D1.D1_FILIAL = D1.D1_FILIAL
					AND SUB_D1.D1_EMISSAO = D1.D1_EMISSAO
					AND SUB_D1.D1_DTDIGIT = D1.D1_DTDIGIT
					AND SUB_D1.D1_ATSAC = D1.D1_ATSAC
					AND SUB_D1.D1_FORNECE = D1.D1_FORNECE
					AND SUB_D1.D1_VUNIT = D1.D1_VUNIT
					AND SUB_D1.D1_TES = D1.D1_TES
					AND SUB_D1.D1_NFORI = D1.D1_NFORI)
				THEN (UD.UD_QTDE * D1.D1_VUNIT)
				ELSE (D1.D1_QUANT * D1.D1_VUNIT)
				END) AS D1_TOTAL,

                D1.D1_TES   , UD.UD_OCORREN, D1.D1_DESCOCO,
                D1.D1_ICMSRET+D1.D1_VALICM+D1.D1_VALIMP6+D1.D1_VALIMP5 AS IMPOSTOS,
                D1.D1_NFORI,

                ISNULL((CASE
                            WHEN UD.UD_S_DMERC = 'R1' THEN 'REVISAO EMB 1'
                            WHEN UD.UD_S_DMERC = 'R2' THEN 'REVISAO EMB 2'
                            WHEN UD.UD_S_DMERC = 'RE' THEN 'REPROCESSO'
                            WHEN UD.UD_S_DMERC = 'ES' THEN 'ESTOQUE'
                            WHEN UD.UD_S_DMERC = 'DE' THEN 'DESCARTE'
                            WHEN UD.UD_S_DMERC = 'RF' THEN 'REFATURAMENTO'
                        END),'') AS UD_S_DMERC,

                ISNULL(UD.UD_ASSUNTO,'') AS UD_ASSUNTO,

                ISNULL((SELECT X5.X5_DESCRI FROM SX5010 X5
                        WHERE X5.X5_FILIAL  = UD.UD_FILIAL
                        AND   X5.X5_CHAVE   = UD.UD_ASSUNTO
                        AND   X5.X5_TABELA  = 'T1'
                        AND   X5.D_E_L_E_T_ = '' ),'') AS X5_DESCRI,

                ISNULL(UD.UD_S_MOTCA,'') AS UD_S_MOTCA, U9_DESC, UD_S_DEPTO,UD_S_DEVOL,

				substrING(D1_USERLGI, 11, 1) + substrING(D1_USERLGI, 15, 1) + substrING(D1_USERLGI, 2, 1) + substrING(D1_USERLGI, 6, 1)  +
                substrING(D1_USERLGI, 10, 1) + substrING(D1_USERLGI, 14, 1) + substrING(D1_USERLGI, 1, 1) + substrING(D1_USERLGI, 5, 1)  +
                substrING(D1_USERLGI, 9, 1)  + substrING(D1_USERLGI, 13, 1) + substrING(D1_USERLGI, 17, 1) + substrING(D1_USERLGI, 4, 1) +
                substrING(D1_USERLGI, 8, 1) USUARIO,

				(
					SUBSTRING(D1_USERLGI, 11, 1) + SUBSTRING(D1_USERLGI, 15, 1) + SUBSTRING(D1_USERLGI, 2, 1) + SUBSTRING(D1_USERLGI, 6, 1) +
					SUBSTRING(D1_USERLGI, 10, 1) + SUBSTRING(D1_USERLGI, 14, 1)
				) AS NOME
            
			FROM
                SD1010 D1 (NOLOCK)
            	INNER JOIN SF1010 F1
                    ON  F1.F1_FILIAL  = D1.D1_FILIAL  	AND
                        F1.F1_DOC     = D1.D1_DOC     	AND
                        F1.F1_SERIE   = D1.D1_SERIE   	AND
                        F1.F1_FORNECE = D1.D1_FORNECE 	AND
                        F1.F1_EMISSAO = D1.D1_EMISSAO 	AND
                        F1.F1_STATUS <> ''    			AND
                        F1.D_E_L_E_T_ = '' 
            	INNER JOIN SA1010 A1
                    ON  A1.A1_COD     = D1.D1_FORNECE 	AND
                        A1.A1_LOJA    = D1.D1_LOJA    	AND
                        --A1.A1_VEND BETWEEN %exp:MV_PAR05% AND %exp:MV_PAR06% AND
                        SUBSTRING(A1.A1_CGC,1,8) NOT IN ('24333411') 		 AND
                        A1.D_E_L_E_T_ = '' 
            	INNER JOIN SB1010 B1
                    ON  B1.B1_COD     = D1.D1_COD AND
                        B1.D_E_L_E_T_ = '' 
           
            	LEFT JOIN SUD010 UD
                    ON  UD.UD_FILIAL  = D1.D1_FILIAL AND
                        UD.UD_CODIGO  = D1.D1_ATSAC  AND
                        UD.UD_PRODUTO = D1.D1_COD    AND
						UD.UD_S_CODM = D1.D1_OCORREN AND
						UD.UD_S_MOTCA = D1.D1_DESCOCO AND
						UD.D_E_L_E_T_ = ''
            	LEFT JOIN SU9010 U9
                   ON
                        U9_CODIGO = UD_OCORREN
						AND U9_ASSUNTO = UD_ASSUNTO
						AND U9_FILIAL = UD_FILIAL
                        AND U9.D_E_L_E_T_ = ''
            WHERE
                --D1.D1_DTDIGIT BETWEEN '20240101' AND '20241231' AND
                --D1.D1_FORNECE BETWEEN %exp:MV_PAR03%       AND %exp:MV_PAR04%       AND
                --D1.D1_SERIE   BETWEEN %exp:MV_PAR07%       AND %exp:MV_PAR08%       AND
                D1.D1_TIPO    = 'D'
                AND D1.D_E_L_E_T_ = '' 
				AND D1.D1_ATSAC IN ('016222')
				--%exp:cFiltro% 

				GROUP BY	
				D1.D1_ATSAC, UD.UD_QTDE, D1.D1_QUANT, D1.D1_FILIAL, D1.D1_EMISSAO, D1.D1_DTDIGIT, F1.F1_TIPO, D1.D1_FORNECE, D1.D1_LOJA, A1.A1_NOME, D1.D1_LOCAL,
				A1.A1_GRPVEN, A1.A1_SEGCLI, D1.D1_LOTECTL, A1.A1_MUN, A1.A1_EST, A1.A1_VEND, D1.D1_DOC, B1.B1_GRUPO, D1.D1_SERIE, D1.D1_COD, B1.B1_DESC, B1.B1_UM,
				D1.D1_VUNIT, D1.D1_TES, UD.UD_OCORREN, D1.D1_DESCOCO, D1.D1_ICMSRET, D1.D1_VALICM, D1.D1_VALIMP6, D1.D1_VALIMP5, D1.D1_NFORI, UD.UD_S_DMERC, UD.UD_ASSUNTO,
				UD.UD_FILIAL, UD.UD_S_MOTCA, U9.U9_DESC, UD.UD_S_DEPTO, UD.UD_S_DEVOL, D1.D1_USERLGI,D1.D1_OCORREN,D1.D1_SERIORI, D1.D1_ITEMORI, B1.B1_PSOPC, B1.B1_PESO

            	ORDER BY
                D1.D1_DOC

				